server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    sendfile off;

    location / {
        try_files $uri $uri/ =404;
    }

    location /joke {
        proxy_pass https://official-joke-api.appspot.com/random_joke;
        proxy_ssl_server_name on;
        proxy_set_header Host official-joke-api.appspot.com;
    }
}    

